name: Test dotfile setup on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dotfiles install and test script
        run: |
          set -e
          export CI=1
          git submodule update --init
          cd .setup
          bash install.sh
